### PR TITLE
5.10-2.1.x-imx: various linux-imx-specific fixes

### PR DESCRIPTION
**Pull request by tq-schiffern**
A number of patches that we've either been carrying in our linux-tqmaxx fork for Linux 5.4, or which fix new problems introduced by NXP when porting their patches to Linux 5.10.

### CODE REVIEW

**Comment by otavio** [comment]
@schiffermtq, glad to see TQ contributing. 

@thochstein, please ask for an internal review. NXP can include those in the next release.

@zandrey, @fabioestevam, please review.

**Comment by tq-schiffern** [comment]
If NXP considers these patches for inclusion, it would be great to bring in our previous series (#75) as well.

**Comment by fabioestevam** [comment]
On Thu, Oct 7, 2021 at 8:55 AM Otavio Salvador ***@***.***> wrote:
>
> @schiffermtq, glad to see TQ contributing.
>
> @thochstein, please ask for an internal review. NXP can include those in the next release.
>
> @zandrey, @fabioestevam, please review.

The series looks good to me.

**Comment by thochstein** [comment]
Will do.

**Pull request merged**
