### PR TITLE
Fix reading of thermal grade OTP value on i.MX7D

### PR DESCRIPTION
**Pull request by jait**

### CODE REVIEW

**Comment by otavio** [comment]
Is it fixed in Linux mainline?

@fabioestevam could you review this as well?

**Comment by fabioestevam** [comment]
On Fri, Jun 29, 2018 at 5:45 PM, Otavio Salvador <notifications@github.com>
wrote:

> Is it fixed in Linux mainline?
>
> @fabioestevam <https://github.com/fabioestevam> could you review this as
> well?
>
We need a detailed commit log explaining the original issue and how it
fixes the problem.

What is the thermal grade result prior and after this patch? What MX7D part
number does this fix affect?

It also needs to sent to the U-Boot list for proper review.

Thanks

**Comment by jait** [comment]
This affects at least part MCIMX7D5EVM10SC and probably MCIMX7D5EVM10SD and other extended temperature range models, too (the letter 'E' being the key here). Before this patch these extended temperature range models (-20...105 C) were incorrectly detected as consumer models (0...95 C) and trip points were set accordingly too low. After the commit, the range is detected correctly by the driver.

I don't know about the U-Boot list. Perhaps you point to the right direction or forward this there?

**Comment by jait** [comment]
> Is it fixed in Linux mainline?

If by mainline you mean the Linus tree (https://github.com/torvalds/linux/commits/master/drivers/thermal/imx_thermal.c), then no, it is not fixed there.

**Comment by fabioestevam** [comment]
Hi Jari,

On Mon, Jul 2, 2018 at 2:54 AM, Jari Tenhunen <notifications@github.com>
wrote:

> This affects at least part MCIMX7D5EVM10SC and probably MCIMX7D5EVM10SD
> and other extended temperature range models, too (the letter 'E' being the
> key here). Before this patch these extended temperature range models
> (-20...105 C) were incorrectly detected as consumer models (0...95 C) and
> trip points were set accordingly too low. After the commit, the range is
> detected correctly by the driver.
>
Good. Please add such information into the patch commit log.

You also need to add your Signed-off-by tag.

> I don't know about the U-Boot list. Perhaps you point to the right
> direction or forward this there?
>
U-Boot list is u-boot@lists.denx.de . You need to send it there (preferably
via git send-email).

**Comment by otavio** [comment]
@fabioestevam, in fact, his patch is for the Linux kernel, so it should be fixed on mainline Linux and send upstream. Am I mistaken?

**Comment by jait** [comment]
Added required information to revised commit.

**Comment by fabioestevam** [comment]
Hi Otavio,

On Mon, Jul 2, 2018 at 10:08 AM, Otavio Salvador <notifications@github.com>
wrote:

> @fabioestevam <https://github.com/fabioestevam>, in fact, his patch is
> for the Linux kernel, so it should be fixed on mainline Linux and send
> upstream. Am I mistaken?
>
Ops, sorry. I thought it was a U-Boot patch.

Yes, it would be really nice to fix this in the mainline kernel first.

Jari,

Please generate the patch against mainline kernel and run
./scripts/get_maintainer 0001-yourpatch.patch to see the people and lists
that you need to send this patch to.

Thaks

**Comment by jait** [comment]
Thanks, but it looks like that the mainline kernel doesn't contain the required parent commits that your 4.9-2.0.x-imx tree has. I'll just leave it here.

**Comment by fabioestevam** [comment]
On Mon, Jul 2, 2018 at 11:36 AM, Jari Tenhunen <notifications@github.com>
wrote:

> Thanks, but it looks like that the mainline kernel doesn't contain the
> required parent commits that your 4.9-2.0.x-imx tree has. I'll just leave
> it here.
>
Your reworked patch with the commit log looks good, thanks.

Yes, the fix in mainline needs to be a bit different. Would you have
interest in fixing there as well?

**Pull request merged**
