### PR TITLE
Add initial CODE PixiePro support

### PR DESCRIPTION
**Pull request by code-ing**
PixiePro is a micro-embedded machine based on Freescale i.MX6 Quad CPU. The
board features:
- 802.11ac/nbg WiFi+ Bluetooth Module
- 3G Modem
- Freescale FXOS8700 Accelerometer/Magnetometer Sensor
- Freescale FXAS21002 Gyroscope Sensor
- 2 60-pin expansion connectors

For more details about PixiePro, please refer to: http://www.treats4geeks.org/

Signed-off-by: Valentina Fernandez Alanis valentina.fernandez@code-ing.com

### CODE REVIEW

**Comment by otavio** [comment]
@fabioestevam please review this. I think the indenting is not right.

**Comment by fabioestevam** [comment]
On Wed, Nov 18, 2015 at 10:06 AM, Otavio Salvador notifications@github.com
wrote:

> @fabioestevam https://github.com/fabioestevam please review this. I
> think the indenting is not right.
> 
> Where exactly is the issue?

I have a hard time reviewing from the github interface. Just send me a
patch via git send-email to my gmail address and I can review it.

**Comment by fabioestevam** [comment]
Hi Otavio,

On Wed, Nov 18, 2015 at 10:08 AM, Fabio Estevam festevam@gmail.com wrote:

> On Wed, Nov 18, 2015 at 10:06 AM, Otavio Salvador notifications@github.com
> wrote:
> 
> > @fabioestevam please review this. I think the indenting is not right.
> 
> Where exactly is the issue?
> 
> I have a hard time reviewing from the github interface. Just send me a patch
> via git send-email to my gmail address and I can review it.

Ok, I see indenting issue in the cooling_fan node.

Is this the one you are referring to?

**Comment by otavio** [comment]
Yes.

On Wed, Nov 18, 2015 at 10:26 AM, fabioestevam notifications@github.com
wrote:

> Hi Otavio,
> 
> On Wed, Nov 18, 2015 at 10:08 AM, Fabio Estevam festevam@gmail.com
> wrote:
> 
> > On Wed, Nov 18, 2015 at 10:06 AM, Otavio Salvador <
> > notifications@github.com>
> > wrote:
> > 
> > > @fabioestevam please review this. I think the indenting is not right.
> > 
> > Where exactly is the issue?
> > 
> > I have a hard time reviewing from the github interface. Just send me a
> > patch
> > via git send-email to my gmail address and I can review it.
> 
> Ok, I see indenting issue in the cooling_fan node.
> 
> Is this the one you are referring to?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Freescale/linux-fslc/pull/3#issuecomment-157694722.

## 

Otavio Salvador                             O.S. Systems
http://www.ossystems.com.br        http://code.ossystems.com.br
Mobile: +55 (53) 9981-7854            Mobile: +1 (347) 903-9750

**Comment by otavio** [comment]
Not active. Closing.

**Pull request closed without merging**
