### PR TITLE
ARM: dts: imx6ull: add alias and sound-dai-cells for sai

### PR DESCRIPTION
**Pull request by joerg-krause**
Required for using the simple-audio-card driver.

### CODE REVIEW

**Comment by otavio** [comment]
@fabioestevam could you review it and check if it has been done upstream as well?

**Comment by fabioestevam** [comment]
On Mon, Jan 29, 2018 at 1:24 PM, Otavio Salvador <notifications@github.com>
wrote:

> @fabioestevam <https://github.com/fabioestevam> could you review it and
> check if it has been done upstream as well?
>

imx6ull.dtsi in upstream includes imx6ul.dtsi.

imx6ul.dtsi already has #sound-dai-cells = <0>; so all is well there.

**Comment by otavio** [comment]
You mean we can merge this ?

**Comment by fabioestevam** [comment]
On Mon, Jan 29, 2018 at 1:41 PM, Otavio Salvador <notifications@github.com>
wrote:

> You mean we can merge this ?
>
Yes, this patch is fine.

**Pull request merged**
