### PR TITLE
Some fixes to get this kernel building on yocto master/main

### PR DESCRIPTION
**Pull request by angolini**
This PR fixes the following error messages on meta-freescale/master

```

ERROR: linux-fslc-6.6.36+git-r0 do_package_qa: QA Issue: File /usr/src/debug/linux-fslc/6.6.36+git/lib/oid_registry_data.c in package linux-fslc-src contains reference to TMPDIR [buildpaths]
ERROR: linux-fslc-6.6.36+git-r0 do_package_qa: Fatal QA errors were found, failing task.
```

```
ERROR: linux-fslc-6.6.36+git-r0 do_package_qa: QA Issue: File /usr/src/debug/linux-fslc/6.6.36+git/drivers/tty/vt/consolemap_deftbl.c in package linux-fslc-src contains reference to TMPDIR
File /usr/src/debug/linux-fslc/6.6.36+git/drivers/video/logo/logo_linux_clut224.c in package linux-fslc-src contains reference to TMPDIR [buildpaths]
ERROR: linux-fslc-6.6.36+git-r0 do_package_qa: Fatal QA errors were found, failing task.
```

```
ERROR: linux-fslc-6.6.36+git-r0 do_package_qa: QA Issue: File /usr/src/debug/linux-fslc/6.6.36+git/drivers/video/logo/logo_linux_clut224.c in package linux-fslc-src contains reference to TMPDIR [buildpaths]
ERROR: linux-fslc-6.6.36+git-r0 do_package_qa: Fatal QA errors were found, failing task.
```

### CODE REVIEW

**Comment by fabioestevam** [comment]
Were these 3 patches sent upstream?

**Comment by angolini** [comment]
@fabioestevam I took them from `linux-yocto`, so I haven't researched if they are actually sent upstream (to kernel.org). But goot catch, let me check.

**Comment by angolini** [comment]
2 errors are already merged on some newer linux version:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/video/logo/pnmtologo.c?h=v6.10&id=fb3b9c2d217f1f51fffe19fc0f4eaf55e2d4ea4f

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/lib/build_OID_registry?h=v6.10.1&id=5ef6dc08cfde240b8c748733759185646e654570

but the fix for `vt/conmakehash: improve reproducibility`I could not find.

**Comment by fabioestevam** [comment]
Thanks, so it would be better to use the upstream versions of these two.

I will ask the stable folks to apply them for 6.6.

**Comment by fabioestevam** [comment]
The vt/conmakehash one has been submitted upstream by Max:

https://lore.kernel.org/linux-serial/20240725132056.9151-1-max.oss.09@gmail.com/

Could you please test Max's patch?

**Comment by angolini** [comment]
I can test the 3 of them! Thanks for the link

**Comment by angolini** [comment]
```
8f24666d05968 tty: vt: conmakehash: cope with abs_srctree no longer in env
7ea30dacfb713 lib/build_OID_registry: don't mention the full path of the script in output
0f806d7395704 video: logo: Drop full path of the input filename in generated file
```

@fabioestevam I updated the PR with the kernel.org version for the patches. It worked

**Comment by fabioestevam** [comment]
It looks good, thanks.

**Comment by fabioestevam** [comment]
I asked the stable folks to backport the two fixes into 6.6 stable. Greg KH has queued up both.

About Max's patch, it has the Fixes tag, so it should automatically be applied to 6.6 stable after it lands in mainline.

Maybe it could help if you reply to Max's patch with your Tested-by.

Thanks

**Comment by angolini** [comment]
@fabioestevam , I think I have replied. It took me a while because I was dealing with git send-email configuration ;)

**Comment by fabioestevam** [comment]
> @fabioestevam , I think I have replied. It took me a while because I was dealing with git send-email configuration ;)

Thanks Daiane

**Pull request merged**
