### PR TITLE
5.10.x+fslc

### PR DESCRIPTION
**Pull request by Ossanes**

### CODE REVIEW

**Comment by otavio** [comment]
@zandrey @fabioestevam this was just the `savedefconfig`.  Please review it as well.

**Review by otavio — APPROVED** [review]

**Comment by zandrey** [comment]
@otavio @Ossanes 

I'm afraid that would always come up as a merge conflict during patch level bump every time config files are updated upstream... I know that this happens quite seldom on the LTS branches, but still...

Besides readability, is there any other reason why this should be done?

-- andrey

**Comment by otavio** [comment]
@zandrey I was intending we could send this upstream so we would drop it.

**Comment by zandrey** [comment]
> @zandrey I was intending we could send this upstream so we would drop it.

Honestly, I would be skeptical about that it would be accepted. Usually, SOC maintainers do not like config patches and are trying to keep those at minimum. This is from my experience, see the [discussion on LKML regarding removal of unused BACKLIGHT_GENERIC option](https://lore.kernel.org/linux-arm-kernel/20201130152137.24909-1-andrey.zhizhikin@leica-geosystems.com/). This was merged eventually, but it took a lot of coordination to pull through.

I'm not saying that up-streaming is impossible, but would be very difficult.

Can this be done the other way around: first submit upstream, and if there would be no serious objections - take it here?

-- andrey

**Comment by fabioestevam** [comment]
On Thu, Mar 4, 2021 at 11:06 AM Andrey Zhizhikin
<notifications@github.com> wrote:
>
> @zandrey I was intending we could send this upstream so we would drop it.
>
> Honestly, I would be skeptical about that it would be accepted. Usually, SOC maintainers do not like config patches and are trying to keep those at minimum. This is from my experience, see the discussion on LKML regarding removal of unused BACKLIGHT_GENERIC option. This was merged eventually, but it took a lot of coordination to pull through.
>
> I'm not saying that up-streaming is impossible, but would be very difficult.
>
> Can this be done the other way around: first submit upstream, and if there would be no serious objections - take it here?

I agree with Andrey.

Please see the feedback from the ARM maintainer, Arnd:
https://patchwork.ozlabs.org/project/linux-imx/patch/20210204030316.489-3-alistair@alistair23.me/

He wants a better explanation for the symbols that are removed.

**Comment by otavio** [comment]
Ok then. @Ossanes please drop those and just add the needed config. I'll close this PR so we open a new one for it.

**Comment by Ossanes** [comment]
Ok.



Sent from my Galaxy



-------- Original message --------

**Pull request closed without merging**
