### PR TITLE
rtc: ds1307: Ensure that alarm IRQ can be wakeup source

### PR DESCRIPTION
**Pull request by varigigi**

### CODE REVIEW

**Comment by otavio** [comment]
Have you sent this upstream?

**Comment by varigigi** [comment]
Hi Otavio,
same answer as [pull request 422](https://github.com/Freescale/linux-fslc/pull/422#issuecomment-903105570).
Regards
Pier

**Comment by fabioestevam** [comment]
Hi Pierluigi,

The Author and Signed-off-by tags do not match.

The commit log is empty.

It is a good idea to submit it upstream.

**Comment by varigigi** [comment]
Hi Fabio,
thanks for reporting I can easily fix it.
Is there any guideline to push upstream?
Am I supposed to push to the mainline directly?
Thanks
Regards
Pier

**Comment by fabioestevam** [comment]
Hi Pierluigi,

On Sat, Aug 21, 2021 at 9:05 AM varigigi ***@***.***> wrote:
>
> Hi Fabio,
> thanks for reporting I can easily fix it.
> Is there any guideline to push upstream?

Please check Documentation/process/submitting-patches.rst from the
kernel source.

> Am I supposed to push to the mainline directly?

Please generate your patch against the linux-next tree and send it to the folks
listed in "scripts/get_maintainer.pl 0001-yourpatch"

If you have any issues with the process, just let me know and I can help you.

Regards,

Fabio Estevam

**Comment by fabioestevam** [comment]
Hi Pierluigi,

Could you try passing the "wakeup-source" property in your devicetree?

That should work without any extra kernel patch.

Thanks

**Comment by varigigi** [comment]
Hi Fabio,
actually we (Variscite) do have the the "wakeup-source" property in [our devicetree](https://github.com/varigit/linux-imx/blob/lf-5.10.y_var02/arch/arm64/boot/dts/freescale/imx8mp-var-dart-dt8mcustomboard.dts#L239).
Why do you think the RTC DS1337 should wakeup even without calling the enable_irq_wake function?
I can see a this function call in several RTC drivers, but not in the current rtc-ds1337.c code.
Am I missing any detail ?
Thanks
Regards
Pier

**Comment by fabioestevam** [comment]
On Sat, Aug 21, 2021 at 4:40 PM varigigi ***@***.***> wrote:
>
> Hi Fabio,
> actually we (Variscite) do have the the "wakeup-source" property in our devicetree.
> Why do you think the RTC DS1337 should wakeup even without calling the enable_irq_wake function?

Isn't device_set_wakeup_capable(ds1307->dev, true) being called on your case?

Feel free to submit the patch to the linux-rtc folks.

**Comment by otavio** [comment]
@varigigi have you prepare a patch addressing the @fabioestevam comments?

**Pull request closed without merging**
