### PR TITLE
Merge tag 'v5.4.161' into 5.4-2.3.x-imx

### PR DESCRIPTION
**Pull request by denisdrozdov**
Dear Otavio,

I would like to ask you to push v5.4.161 patches on top of 5.4-2.3.x-imx kernel branch to provide LTS support for the linux-fslc repo on Github [1]. Please find the newest stable patches [2] v5.4.161 on top of the latest 5.4-2.3.x-imx kernel [1] as a base.

[1] https://github.com/Freescale/linux-fslc
[2] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=v5.4.161

Build Verified on following targets ( including rt support):
- NXP iMX8X
- NXP iMX8
- NXP iMX8M Mini
- NXP iMX8M Plus

### CODE REVIEW

**Comment by otavio** [comment]
@zandrey, could you take a look?

**Comment by zandrey** [comment]
@denisdrozdov 

The support for `5.4-2.3.x-imx` has been dropped with #458, while layer has moved to use `5.10-2.1.x-imx` instead for `linux-fslc-imx`.

While I do not mind (and actually appreciate) that any Kernel branch here is maintained further, maybe it is beneficial to mention for which branch in _meta-freescale_ `5.4-2.3.x-imx` is targeted? From what I see, either `5.4-2.1.x-imx` or `5.10-2.1.x-imx` are used now in `linux-fslc-imx`.

Also, if you have any conflicts resolved during merge - please list those in corresponding merge commit message, it would be easier to track down issues coming out of those.

-- andrey

**Comment by otavio** [comment]
@denisdrozdov as @zandrey mentioned, would it be possible to go to newer branches? 5.10 seems very appealing and would allow for a widely used branch to be used.

**Comment by denisdrozdov** [comment]
Dear @zandrey and @otavio

The merge of `v5.4.161` to `5.4-2.3.x-imx` contains the latest long-term support and real-time patches for Linux kernel  5.4.
available here https://cdn.kernel.org/pub/linux/kernel/projects/rt/5.4/older/patch-5.4.161-rt67.patch.gz

`5.4-2.1.x-imx`  is way too outdated  with the latest commit made on `May 30 2020`
https://source.codeaurora.org/external/imx/linux-imx/commit/?h=imx_5.4.24_2.1.0&id=babac008e5cf168abca1a85bda2e8071ca27a5c0.

***It would be very beneficial for BSP and hardware vendors using Linux kernel 5.4 to use NXP BSP 5.4.70-2.3.2 release to keep the community kernel up to date.***

`Dunfell` based layer could use `BSP 5.4.70-2.3.2` branch `5.4-2.3.x-imx`  that has a number of fixes and up-to-date kernel source base with a recent NXP commits, instead of  `5.4-2.1.x-imx` , as it proved to work on a major set of iMX targets.

 `meta-freescale` branch `dunfell` could use L5.4.70-2.3.2  kernel branch `5.4-2.3.x-imx` in `linux-fslc-imx` instead of outdated `5.4-2.1.x-imx` kernel branch, in some custom build or other vendors might be doing in their own layers.

Moving to `thochstein/5.10` would be better for the long-term support, but it would require migration from `dunfell`

As there are no conflicts, except cosmetic changes have been resolved, I would suggest keeping this branch up to date for the latest long-term support and real-time support.

**Comment by zandrey** [comment]
Hello @denisdrozdov 

> Dear @zandrey and @otavio
> 
> The merge of `v5.4.161` to `5.4-2.3.x-imx` contains the latest long-term support and real-time patches for Linux kernel 5.4. available here https://cdn.kernel.org/pub/linux/kernel/projects/rt/5.4/older/patch-5.4.161-rt67.patch.gz

To be complete, this is not latest LTS kernel version (latest being _5.4.170_) but rather latest LTS which has RT-patch applied on top.

> 
> `5.4-2.1.x-imx` is way too outdated with the latest commit made on `May 30 2020` https://source.codeaurora.org/external/imx/linux-imx/commit/?h=imx_5.4.24_2.1.0&id=babac008e5cf168abca1a85bda2e8071ca27a5c0.

I depends on the definition of "_outdated_". In the context of _Vendor Kernel_ it might well be, but in the context of LTS patch level - it is quite current, as I tend to keep it up-to-date to be used in `dunfell` branch on _meta-freescale_.

> 
> _**It would be very beneficial for BSP and hardware vendors using Linux kernel 5.4 to use NXP BSP 5.4.70-2.3.2 release to keep the community kernel up to date.**_

Again, provided that vendors in your context do use NXP vendor Kernl, and the upstream one.

> 
> `Dunfell` based layer could use `BSP 5.4.70-2.3.2` branch `5.4-2.3.x-imx` that has a number of fixes and up-to-date kernel source base with a recent NXP commits, instead of `5.4-2.1.x-imx` , as it proved to work on a major set of iMX targets.

This has a consequence that the entire layer's `dunfell` branch should be upgraded to NXP release 2.3.2, which is highly unlikely to happen for LTS Yocto release.

Kernel recipe is synchronized with NXP release, and `dufell` branch contains only release 2.1.x.

> 
> `meta-freescale` branch `dunfell` could use L5.4.70-2.3.2 kernel branch `5.4-2.3.x-imx` in `linux-fslc-imx` instead of outdated `5.4-2.1.x-imx` kernel branch, in some custom build or other vendors might be doing in their own layers.

These are vendor-specific policies, _meta-freescale-3rdparty_ layer partially covers this aspect.

> 
> Moving to `thochstein/5.10` would be better for the long-term support, but it would require migration from `dunfell`

This is what is currently used in `master`, which will become a base for next [Yocto LTS Release 3.5 "Kirkstone"](https://wiki.yoctoproject.org/wiki/Releases). You are free to base your design on the `master` now to benefit from next LTS.

> 
> As there are no conflicts, except cosmetic changes have been resolved, I would suggest keeping this branch up to date for the latest long-term support and real-time support.

If you're willing to step-up and take maintenanceship of this branch - I have no objections here! As I've previously stated already: I'd be happy if someone finds those branches useful and continue to maintain them till respective EOLs in upstream. But in this case, what should not be expected in the usage of those branches in the upstream _meta-freescale_ layer since those branches are not aligned with the layer structure in terms of NXP release integration. Custom solutions is always an option though.

Please also note, that there is no RT Kernel recipe that is provided in _meta-freescale_, especially those that are based off the Vendor downstream tree. There is simply no guarantee that the downstream vendor Kernel (with all modifications and additional customized drivers) would be 100% RT-compliant. I cannot and will not recommend anyone to base their RT designs on Vendor Kernels, considering that usually those designs are "_mission-critical_". The choice however lies in hands of system integrators...

-- andrey

**Comment by otavio** [comment]
@denisdrozdov are you willing to keep maintaining this branch?

**Comment by denisdrozdov** [comment]
> @denisdrozdov are you willing to keep maintaining this branch?

Dear @otavio:
Considering @zandrey comment that  `it should not be expected in the usage of those branches in the upstream meta-freescale layer since those branches are not aligned with the layer structure in terms of NXP release integration.`

I would rather continue maintenance of this branch as a  custom solution (option). 
Please be sure, this PR has been validated on the number of targets

**Comment by otavio** [comment]
@denisdrozdov great; I merged it as you intend to keep maintaining it.

**Comment by denisdrozdov** [comment]
> @denisdrozdov great; I merged it as you intend to keep maintaining it.

Great, thank you @otavio. We will have a number of PRs going forward

**Comment by zandrey** [comment]
@denisdrozdov Great! 👍🏻 

One small question regarding your last patch you've added to the PR: is 0156d95 a candidate for upstream? Do you see the same crash in mainline Kernel? If so - can you perhaps send it over to Kernel ML as well?

-- andrey

**Comment by denisdrozdov** [comment]
> @denisdrozdov Great! 👍🏻
> 
> One small question regarding your last patch you've added to the PR: is [0156d95](https://github.com/Freescale/linux-fslc/commit/0156d956a951c70743d2338132662b29aeb8847d) a candidate for upstream? Do you see the same crash in mainline Kernel? If so - can you perhaps send it over to Kernel ML as well?
> 
> -- andrey

> [0156d95](https://github.com/Freescale/linux-fslc/commit/0156d956a951c70743d2338132662b29aeb8847d) a candidate for upstream?

Hi @zandrey.  Commit 0156d95 is not an upstream candidate at the moment. This patch is specific to NXP BSP 5.4.70-2.3.2 kernel and related to another NXP commit 35688521a2 ("MLKU-114-1 crypto: caam - reduce page 0 regs access to minimum").  
In case these NXP specific commits will be available upstream, it will be possible to evaluate this patch going forward.

**Comment by otavio** [comment]
Just one side note. As mentioned by @zandrey please consider upgrading to 5.10 for new developments as it is the main focus for now.

**Comment by denisdrozdov** [comment]
> Just one side note. As mentioned by @zandrey please consider upgrading to 5.10 for new developments as it is the main focus for now.

Sure, @otavio. Thank you.

**Pull request merged**
