### PR TITLE
4.17.x+fslc

### PR DESCRIPTION
**Pull request by schnitzeltony**
@fabioestevam @otavio 

* 1st patch was proposed in meta-freescale mailing list
* 2nd patch is just helpful..

### CODE REVIEW

**Comment by fabioestevam** [comment]
Hi Andreas,

On Thu, Sep 20, 2018 at 6:03 AM, Andreas Müller <notifications@github.com>
wrote:

> @fabioestevam <https://github.com/fabioestevam> @otavio
> <https://github.com/otavio>
>
>    - 1st patch was proposed in meta-freescale mailing list
>    - 2nd patch is just helpful..
>
> Both patches look good.

Otavio,

4.17 is in end of life status. Any plans to bump to 4.18?

**Comment by schnitzeltony** [comment]
If nobody complains, I can take care tomorrow. Hope no regressions won't pop up..

**Comment by otavio** [comment]
Please do. I ported most of your patches. Those new need to be out there as well.

**Comment by otavio** [comment]
As agreed, it will be worked on for 4.18 so I am closing this PR.

**Pull request closed without merging**
