### PR TITLE
4.9 1.0.x imx stable merge

### PR DESCRIPTION
**Pull request by fabioestevam**
Merge 4.9.84 and fixed imx wdog driver conflict.

### CODE REVIEW

**Comment by otavio** [comment]
@fabioestevam when you branched, you did it from 4.1 version so I couldn't merge the pull request as it was targeting the wrong branch. I manually merged your branch and pushed it.

I am then closing this.

**Comment by joerg-krause** [comment]
Mind to create a tag, e.g. rel-4.9.84-1.0.x-imx? A tag makes it easier to integrate the repository into Buildroot, otherwise the commit hash value has to be used.

**Comment by otavio** [comment]
Why? Should it follow the SRCREV no?

**Comment by fabioestevam** [comment]
On Tue, Feb 27, 2018 at 6:35 AM, Otavio Salvador <notifications@github.com>
wrote:

> @fabioestevam <https://github.com/fabioestevam> when you branched, you
> did it from 4.1 version so I couldn't merge the pull request as it was
> targeting the wrong branch. I manually merged your branch and pushed it.
>

Ops, sorry about that. Thanks for manually fixing it!

**Comment by joerg-krause** [comment]
@otavio Buildroot performs a full clone if a hash is used as version, otherwise it does a shallow clone.

**Comment by otavio** [comment]
It seems like a defect.

I think cloning the full repository reduces the future downloads on every revision change and this is the strategy used by the BitBake fetcher module.

I am against the tagging as it is a branch that keeps receiving changes so tagging it with a version is misleading.

**Pull request closed without merging**
