### PR TITLE
drivers: tty: imx: fix flags of rs485 not work properly

### PR DESCRIPTION
**Pull request by lc-wang**
The rs485.flags are lost in functions such as imx_uart_stop_tx(), causing the function of RS485 to be invalid when using the serial port as the RS485 port. Use a variable to store the state to avoid this issue.

### CODE REVIEW

**Review by MrCry0 — APPROVED** [review]

**Comment by otavio** [comment]
Have these been sent to upstream?

**Comment by lc-wang** [comment]
No, not yet.
NXP officials recommend that I push commit here first.
Is it feasible to push to the mainline?

**Comment by otavio** [comment]
Yes, please prepare a patch and send to the Linux kernel mailing list for them to review. And in case there is any changes, please synchronize the changes here.

**Comment by fabioestevam** [comment]
> No, not yet. NXP officials recommend that I push commit here first. Is it feasible to push to the mainline?

You forgot your Signed-off-by tag.

Actually, it is better to send upstream first, copy stable and then it gets backported to 6.6.

**Comment by lc-wang** [comment]
OK, I will attempt to send it to the Linux kernel mailing list for review. 
Also, should I create a new commit with Signed-off here?

**Pull request merged**
